apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: taskwarrior
  labels:
    app: web
  annotations:
    tailscale.com/expose: "true"
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
