apiVersion: v1
kind: Service
metadata:
  name: webui-svc
  namespace: taskwarrior
  labels:
    app: webui
  annotations:
    tailscale.com/expose: "true"
spec:
  type: NodePort
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
