- name: Clone/pull self-hosting repo
  hosts: all

  roles:
  - role: ~/Workspace/workspace/self-hosting/ansible/roles/git_repo
    vars:
      git_repo_url: https://github.com/austinsherron/self-hosting.git
      git_dest_dir: ~/Workspace/workspace/self-hosting

- name: "Import Nextcloud playbook"
  ansible.builtin.import_playbook: nextcloud.yaml

- name: "Import Taskwarrior Web UI playbook"
  ansible.builtin.import_playbook: taskwarrior.yaml
