- name: Run Nextcloud Terraform
  hosts: all

  roles:
  - role: ~/Workspace/workspace/self-hosting/ansible/roles/terraform
    vars:
      component_name: Nextcloud
      terraform_dir: ~/Workspace/workspace/self-hosting/apps/nextcloud
