- name: Run Nextcloud Terraform
  hosts: all

  vars:
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    play: "{{ lookup('env', 'PLAY') | default('nextcloud', true) }}"

  pre_tasks:
    - name: Exit if play != nextcloud
      meta: end_play
      when: play != 'nextcloud'

  roles:
  - role: ~/Workspace/workspace/self-hosting/ansible/roles/terraform
    vars:
      component_name: Nextcloud
      terraform_dir: ~/Workspace/workspace/self-hosting/apps/nextcloud
      tf_flags: >
        -no-color
        -var postgres_password={{ postgres_password }}
