- name: Run Taskwarrior Web UI Terraform
  hosts: all

  vars:
    play: "{{ lookup('env', 'PLAY') | default('taskwarrior', true) }}"

  pre_tasks:
    - name: Exit if play != taskwarrior
      meta: end_play
      when: play != 'taskwarrior'

  tasks:
    - name: Apply Task namespace
      kubernetes.core.k8s:
        state: present
        kubeconfig: ~/.kube/config
        src: ~/Workspace/workspace/self-hosting/apps/taskwarrior/namespace.yaml

    - name: Apply Taskwarrior Web UI deployment
      kubernetes.core.k8s:
        state: present
        kubeconfig: ~/.kube/config
        src: ~/Workspace/workspace/self-hosting/apps/taskwarrior/web-ui/deploy.yaml

    - name: Apply Taskwarrior Web UI service
      kubernetes.core.k8s:
        state: present
        kubeconfig: ~/.kube/config
        src: ~/Workspace/workspace/self-hosting/apps/taskwarrior/web-ui/svc.yaml
