- name: Clone/pull self-hosting repo
  hosts: all

  roles:
  - role: ~/Workspace/workspace/self-hosting/ansible/roles/git_repo
    vars:
      git_repo_url: https://github.com/austinsherron/self-hosting.git
      git_dest_dir: ~/Workspace/workspace/self-hosting
      git_branch: feature/nextcloud-pv

- name: "Import microk8s playbook"
  ansible.builtin.import_playbook: microk8s.yaml

- name: "Import nfs playbook"
  ansible.builtin.import_playbook: nfs.yaml

- name: "Import tailscale playbook"
  ansible.builtin.import_playbook: tailscale.yaml

- name: "Import volume playbook"
  ansible.builtin.import_playbook: volume.yaml
