- name: Mount NFS volumes and update fstab
  hosts: all
  become: true

  vars:
    play: "{{ lookup('env', 'PLAY') | default('nfs', true) }}"

  pre_tasks:
    - name: Exit if play != nfs
      meta: end_play
      when: play != 'nfs'

  roles:
    - role: ~/Workspace/workspace/self-hosting/ansible/roles/mount_nfs
      vars:
        mount_point: "/mnt/apps"
        nfs_ip: "192.168.12.178"
        nfs_share: "/nfs/apps"

    - role: ~/Workspace/workspace/self-hosting/ansible/roles/mount_nfs
      vars:
        mount_point: "/mnt/austin"
        nfs_ip: "192.168.12.178"
        nfs_share: "/nfs/austin"
