- name: Run Tailscale terraform
  hosts: all

  vars_prompt:
    - name: oauth_client_id
      prompt: k8s-operator oauth client ID
      private: true

    - name: oauth_client_secret
      prompt: password for the k8s-operator oauth client
      private: true

  vars:
    tf_flags: >
      -no-color
      -var oauth_client_id={{ oauth_client_id }}
      -var oauth_client_secret={{ oauth_client_secret }}

  tasks:
    - name: Initialize Terraform
      command:
        cmd: terraform init
        chdir: "~/Workspace/workspace/self-hosting/infra/tailscale/terraform"

    - name: Run Tailscale Terraform plan
      command:
        cmd: terraform plan {{ tf_flags }}
        chdir: "~/Workspace/workspace/self-hosting/infra/tailscale/terraform"
      register: plan_output

    - name: Display Tailscale Terraform plan
      debug:
        msg: "{{ plan_output.stdout }}"

    - name: Apply Terraform
      command:
        cmd: terraform apply -auto-approve {{ tf_flags }}
        chdir: "~/Workspace/workspace/self-hosting/infra/tailscale/terraform"
