- name: Run Tailscale Terraform
  hosts: all

  vars:
    oauth_client_id: "{{ lookup('env', 'TAILSCALE_OAUTH_CLIENT_ID') }}"
    oauth_client_secret: "{{ lookup('env', 'TAILSCALE_OAUTH_CLIENT_SECRET') }}"
    play: "{{ lookup('env', 'PLAY') | default('tailscale', true) }}"

  pre_tasks:
    - name: Exit if play != tailscale
      meta: end_play
      when: play != 'tailscale'

  roles:
  - role: ~/Workspace/workspace/self-hosting/ansible/roles/terraform
    vars:
      component_name: Tailscale
      terraform_dir: ~/Workspace/workspace/self-hosting/infra/tailscale
      tf_flags: >
        -no-color
        -var oauth_client_id={{ oauth_client_id }}
        -var oauth_client_secret={{ oauth_client_secret }}
