- name: Apply PersistentVolume Kubernetes resources
  hosts: servers

  vars:
    play: "{{ lookup('env', 'PLAY') | default('volume', true) }}"

  pre_tasks:
    - name: Exit if play != volume
      meta: end_play
      when: play != 'volume'

  tasks:
    - name: Apply nfs StorageClass
      kubernetes.core.k8s:
        state: present
        kubeconfig: ~/.kube/config
        src: ~/Workspace/workspace/self-hosting/infra/volume/nfs-sc.yaml

    - name: Apply apps-volume PersistentVolume
      kubernetes.core.k8s:
        state: present
        kubeconfig: ~/.kube/config
        src: ~/Workspace/workspace/self-hosting/infra/volume/apps-pv.yaml
