apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: dcsunset/taskwarrior-webui:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        # env:
        # - name: TASKRC
        #   value: "/path/to/taskrc" # Replace with the actual path to your taskrc file if needed
        # - name: TASKDATA
        #   value: "/path/to/taskdata" # Replace with the actual path to your task data
---
apiVersion: v1
kind: Service
metadata:
  name: webui-svc
  labels:
    app: webui
spec:
  type: NodePort
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
