apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-volume
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.12.178
    path: /nfs/apps
